title:              etcsetera
email:              mdwhitmeyer@gmail.com
description:        theoretical computer science, but mainly etcetera
author:             Michael Whitmeyer
baseurl:            /blog/
url:                "https://mwhitmeyer.github.io"
permalink:          /:title

# Social Profiles
twitter_username:   mdwhitmeyer
github_username:    mwhitmeyer
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-187287555-1 # out your google-analytics code

# Build settings
theme:              jekyll-theme-clean-blog
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-latex